---
- hosts: slave_nodes
  tasks:
  
  - name: "Copy Hadoop"
    copy: 
     src: "/var/www/cgi-bin/Hadoop-Cluster/softwares/hadoop-1.2.1-1.x86_64.rpm"
     dest: "/root/Downloads/hadoop-1.2.1-1.x86_64.rpm"

  - name: "Copy Java"
    copy: 
     src: "/var/www/cgi-bin/Hadoop-Cluster/softwares/jdk-8u171-linux-x64.rpm"
     dest: "/root/Downloads/jdk-8u171-linux-x64.rpm"

  - name: "Installing Java"
    package: 
     name: "/root/Downloads/jdk-8u171-linux-x64.rpm"
     state: "present"

  - name: "Installing Hadoop"
    command: "rpm -i /root/Downloads/hadoop-1.2.1-1.x86_64.rpm --force"

  - lineinfile:
     path: "/root/.bashrc"
     line: "export JAVA_HOME=/usr/java/jdk1.8.0_171-amd64/ \nexport PATH=/usr/java/jdk1.8.0_171-amd64/bin/:$PATH"
     state: "present"
     create: "yes"
     insertafter: EOF

  - template:
     src: "/var/www/cgi-bin/Hadoop-Cluster/files/slave-hdfs-site.xml.j2"
     dest: "/etc/hadoop/hdfs-site.xml"

  - template:
     src: "/var/www/cgi-bin/Hadoop-Cluster/files/slave-core-site.xml.j2"
     dest: "/etc/hadoop/core-site.xml"

  - template:
     src: "/var/www/cgi-bin/Hadoop-Cluster/files/slave-mapred-site.xml.j2"
     dest: "/etc/hadoop/mapred-site.xml"
  
  - name: "making Folder"
    file:
     path: "/data"
     state: "directory"
     mode: 0755

  - name: "Starting Hadoop Service"
    command: "hadoop-daemon.sh start datanode; hadoop-daemon.sh start tasktracker"

  - firewalld:
     port: "{{item}}"
     immediate: "True"
     permanent: "True"
     state: "enabled"
    with_items:
    - "9001/tcp"
    - "9002/tcp"
    - "50030/tcp"
    - "50070/tcp"
...
